wandb_version: 1

train_file:
  desc: null
  value: /home/shu4/ECE491B_HW1/data/Experiment_output/tinystories_train_tokens.npy
val_file:
  desc: null
  value: /home/shu4/ECE491B_HW1/data/Experiment_output/tinystories_valid_tokens.npy
checkpoint_dir:
  desc: null
  value: /home/shu4/ECE491B_HW1/data/Experiment_output/tinystories_checkpoints
wandb_project:
  desc: null
  value: transformer-lm
vocab_size:
  desc: null
  value: 50000
context_length:
  desc: null
  value: 128
d_model:
  desc: null
  value: 512
num_layers:
  desc: null
  value: 6
num_heads:
  desc: null
  value: 8
d_ff:
  desc: null
  value: 2048
attn_pdrop:
  desc: null
  value: 0.1
residual_pdrop:
  desc: null
  value: 0.1
batch_size:
  desc: null
  value: 32
total_iters:
  desc: null
  value: 10000
lr:
  desc: null
  value: 0.0005
lr_min:
  desc: null
  value: 1.0e-05
warmup_iters:
  desc: null
  value: 1000
weight_decay:
  desc: null
  value: 0.001
beta1:
  desc: null
  value: 0.9
beta2:
  desc: null
  value: 0.999
eps:
  desc: null
  value: 1.0e-08
max_norm:
  desc: null
  value: 1
log_interval:
  desc: null
  value: 100
checkpoint_interval:
  desc: null
  value: 500
no_cuda:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    python_version: 3.11.8
    cli_version: 0.19.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1739775804
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 3
      - 14
      - 16
      - 23
      - 37
      - 61
      4: 3.11.8
      5: 0.19.1
      8:
      - 2
      - 5
      13: linux-x86_64
